enableGlobalCache: true
nmMode: hardlinks-global
packageExtensions:
  "@graphql-codegen/cli@2.8.0":
    dependencies:
      tslib: npm:tslib@^2.4.0
  "@parcel/cache@^2.6.0":
    dependencies:
      "@parcel/core": ^2.6.0
  "@parcel/fs@^2.6.0":
    dependencies:
      "@parcel/core": ^2.6.0
  "@parcel/package-manager@^2.6.0":
    dependencies:
      "@parcel/core": ^2.6.0
  "@parcel/workers@^2.6.0":
    dependencies:
      "@parcel/core": ^2.6.0
  chalk@5.0.1:
    dependencies:
      "#ansi-styles": npm:ansi-styles@6.1.0
      "#supports-color": npm:supports-color@9.2.2
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
yarnPath: .yarn/releases/yarn-3.2.1.cjs
