name: Stub publish test

# by following this [guide](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks)

on:
  push:
    branches-ignore:
      - master
    paths-ignore:
      - native-app/**
      - chrome-extension/**
      - .releaserc.yml
      - '.github/workflows/publish-test.yml'
      - '!**.md'

jobs:
  test-release:
    runs-on: ubuntu-22.04
    steps:
      - run: echo Ok
